name: Deploy to Production

on: workflow_dispatch

env:
  INSTALL:  
  SSH_HOST: 

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        name: deploy-wpengine
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Upload files
      run: |
        rsync -chavP \
          -e 'ssh -i ~/.ssh/deploy-wpengine' \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /.gitignore \
          --exclude /.ssh/ \
          wp-content/ "$INSTALL@$SSH_HOST:/sites/$INSTALL/wp-content/"

    - name: Clear caches
      run: ssh -i ~/.ssh/deploy-wpengine $INSTALL@$SSH_HOST 'wp cache flush; wp page-cache flush; wp cdn-cache flush'

  clear-caches:
    runs-on: ubuntu-latest
    needs: [ deploy ]

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        name: deploy-wpengine
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Clear caches
      run: ssh -i ~/.ssh/deploy-wpengine $INSTALL@$SSH_HOST 'wp cache flush; wp page-cache flush; wp cdn-cache flush'
