name: Deploy to Dev

on: workflow_dispatch

env:
  INSTALL:  
  SSH_HOST: 

jobs:

  backup-plugins:
    runs-on: ubuntu-latest
    steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        name: deploy-wpengine
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Backup plugins
      run: ssh -i ~/.ssh/deploy-wpengine $INSTALL@$SSH_HOST 'zip -r --filesync --test --display-bytes --display-counts sites/${{ env.INSTALL }}/_wpeprivate/backup-plugins.zip sites/${{ env.INSTALL }}/wp-content/plugins'

  backup-muplugins:
    runs-on: ubuntu-latest
    steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        name: deploy-wpengine
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Backup mu-plugins
      run: ssh -i ~/.ssh/deploy-wpengine $INSTALL@$SSH_HOST 'zip -r --filesync --test --display-bytes --display-counts sites/${{ env.INSTALL }}/_wpeprivate/backup-muplugins.zip sites/${{ env.INSTALL }}/wp-content/mu-plugins'

  backup-themes:
    runs-on: ubuntu-latest
    steps:

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        name: deploy-wpengine
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Backup themes
      run: ssh -i ~/.ssh/deploy-wpengine $INSTALL@$SSH_HOST 'zip -r --filesync --test --display-bytes --display-counts sites/${{ env.INSTALL }}/_wpeprivate/backup-themes.zip sites/${{ env.INSTALL }}/wp-content/themes'

  deploy:
    runs-on: ubuntu-latest
    needs: [ backup-plugins, backup-muplugins, backup-themes ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        name: deploy-wpengine
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Upload files
      run: |
        rsync -chavP \
          -e 'ssh -i ~/.ssh/deploy-wpengine' \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /.gitignore \
          --exclude /.ssh/ \
          wp-content/ "$INSTALL@$SSH_HOST:/sites/$INSTALL/wp-content/"

  clear-caches:
    runs-on: ubuntu-latest
    needs: [ deploy ]

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        name: deploy-wpengine
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Clear caches
      run: ssh -i ~/.ssh/deploy-wpengine $INSTALL@$SSH_HOST 'wp cache flush; wp page-cache flush; wp cdn-cache flush'
